export const SendNotificationEvent = {
  INCOMING_SAFE_NOTE: 'INCOMING_SAFE_NOTE',
  TEAM_MEMBER_REQUEST: 'TEAM_MEMBER_REQUEST',
  SIGNED_SAFE_NOTE: 'SIGNED_SAFE_NOTE',
  PAYED_SAFE_NOTE: 'PAYED_SAFE_NOTE',
};
