export enum PlaidWebhookType {
  TRANSFER = 'TRANSFER',
  ITEM = 'ITEM',
}

export enum PlaidTransferWebhookCode {
  TRANSFER_EVENTS_UPDATE = 'TRANSFER_EVENTS_UPDATE',
  RECURRING_NEW_TRANSFER = 'RECURRING_NEW_TRANSFER',
  RECURRING_TRANSFER_SKIPPED = 'RECURRING_TRANSFER_SKIPPED',
  RECURRING_CANCELLED = 'RECURRING_CANCELLED',
}
